# Numpy

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
c = a + b
d = np.arange(8)
d.reshape(4, 2)
np.linspace(0, 2, num=11)


array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [2]:
import numpy as np

# Each row is a training example, each column is a feature  [X1, X2, X3]
X = np.array(([0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]), dtype=float)
y = np.array(([0], [1], [1], [0]), dtype=float)

# Define useful functions

# Activation function
def sigmoid(t):
    return 1 / (1 + np.exp(-t))


# Derivative of sigmoid
def sigmoid_derivative(p):
    return p * (1 - p)


# Class definition
class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        self.weights1 = np.random.rand(
            self.input.shape[1], 4
        )  # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(4, 1)
        self.y = y
        self.output = np.zeros(y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2

    def backprop(self):
        d_weights2 = np.dot(
            self.layer1.T, 2 * (self.y - self.output) * sigmoid_derivative(self.output)
        )
        d_weights1 = np.dot(
            self.input.T,
            np.dot(
                2 * (self.y - self.output) * sigmoid_derivative(self.output),
                self.weights2.T,
            )
            * sigmoid_derivative(self.layer1),
        )

        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, X, y):
        self.output = self.feedforward()
        self.backprop()


NN = NeuralNetwork(X, y)
for i in range(1001):  # trains the NN 1,000 times
    if i % 100 == 0:
        print("for iteration # " + str(i) + "\n")
        print("Input : \n" + str(X))
        print("Actual Output: \n" + str(y))
        print("Predicted Output: \n" + str(NN.feedforward()))
        print(
            "Loss: \n" + str(np.mean(np.square(y - NN.feedforward())))
        )  # mean sum squared loss
        print("\n")
        print("Layer 1: \n" + str(NN.layer1))
        print("\n")

    NN.train(X, y)

for iteration # 0

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.72566269]
 [0.75334452]
 [0.75836412]
 [0.78005202]]
Loss: 
0.313573579550288


Layer 1: 
[[0.56570494 0.61451868 0.54346212 0.56709   ]
 [0.6313528  0.65293811 0.75640461 0.70136411]
 [0.72902257 0.61625936 0.74321464 0.59861713]
 [0.77960146 0.65460282 0.88303848 0.72780618]]


for iteration # 100

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.46980893]
 [0.50139325]
 [0.52731077]
 [0.53243998]]
Loss: 
0.24406414103905177


Layer 1: 
[[0.57678847 0.62304912 0.55012231 0.56383382]
 [0.80077394 0.67087989 0.7738889  0.69855184]
 [0.81975479 0.63122741 0.76038012 0.56814275]
 [0.93061805 0.67855583 0.89880362 0.70223274]]


for iteration # 200

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.23884547]